apiVersion: v1
kind: Pod
metadata:
  name: some-postgres
  labels:
    name: some-postgres
spec:
  containers:
    - image: launcher.gcr.io/google/postgresql11
      name: postgres
      env:
        - name: POSTGRES_DB
          value: pm-db
