apiVersion: v1
kind: Pod
metadata:
  name: some-postgres
  labels:
    name: some-postgres
spec:
  containers:
    - image: launcher.gcr.io/google/postgresql11
      name: postgres
      env:
        - name: POSTGRES_USER
          value: pmuser
        - name: PGUSER
          value: pmuser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pass
              key: password.txt
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
